//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebASPMVC_BS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FEEDBACK
    {
        public int id_usr_fbk_prov { get; set; }
        public Nullable<int> id_usr_fbk_rec { get; set; }
        public Nullable<int> id_item { get; set; }
        public Nullable<int> id_swap { get; set; }
        public string id_blocked { get; set; }
        public string am_rating { get; set; }
        public string tx_feedback { get; set; }
    }
}
