//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebASPMVC_BS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class FirstDBEntities : DbContext
    {
        public FirstDBEntities()
            : base("name=FirstDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TRACK> TRACKs { get; set; }
        public DbSet<USER> USERS { get; set; }
        public DbSet<ITEM> ITEMs { get; set; }
        public DbSet<SWAP> SWAPs { get; set; }
        public DbSet<USR_COM> USR_COM { get; set; }
        public DbSet<FEEDBACK> FEEDBACKs { get; set; }
        public DbSet<ITEM_IMG> ITEM_IMG { get; set; }
    
        public virtual int delete_track(Nullable<int> in_id)
        {
            var in_idParameter = in_id.HasValue ?
                new ObjectParameter("in_id", in_id) :
                new ObjectParameter("in_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_track", in_idParameter);
        }
    
        public virtual int fetch_tracks(Nullable<int> in_id)
        {
            var in_idParameter = in_id.HasValue ?
                new ObjectParameter("in_id", in_id) :
                new ObjectParameter("in_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("fetch_tracks", in_idParameter);
        }
    
        public virtual int insert_track(Nullable<int> in_id, string in_name, string in_description)
        {
            var in_idParameter = in_id.HasValue ?
                new ObjectParameter("in_id", in_id) :
                new ObjectParameter("in_id", typeof(int));
    
            var in_nameParameter = in_name != null ?
                new ObjectParameter("in_name", in_name) :
                new ObjectParameter("in_name", typeof(string));
    
            var in_descriptionParameter = in_description != null ?
                new ObjectParameter("in_description", in_description) :
                new ObjectParameter("in_description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_track", in_idParameter, in_nameParameter, in_descriptionParameter);
        }
    }
}
