//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebASPMVC_BS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_IMG
    {
        public int id_item { get; set; }
        public Nullable<int> id_img { get; set; }
        public byte[] blob_img { get; set; }
    }
}
