//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebASPMVC_BS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM
    {
        public int id { get; set; }

        public int id_orig_owner { get; set; }
       
        public string dscr_short { get; set; }
        public string dscr_full { get; set; }
        public string typ_condition { get; set; }
        public byte[] blb_img { get; set; }
    }
}
