//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebASPMVC_BS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SWAP
    {
        public long id { get; set; }
        public Nullable<int> id_usr_offer { get; set; }
        public Nullable<int> id_item_offered { get; set; }
        public Nullable<int> id_usr_agreed { get; set; }
        public Nullable<int> id_item_agreed { get; set; }
        public string id_swp_status { get; set; }
        public string tx_notes { get; set; }
    }
}
