//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebASPMVC_BS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TRACK
    {
        public int id { get; set; }

        [Display(Name = "User Name")]
        public string name { get; set; }

        [Display(Name = "Description")]
        public string description { get; set; }
    }
}
