//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebASPMVC_BS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USR_COM
    {
        public int id_item { get; set; }
        public int id_swp { get; set; }
        public Nullable<int> id_usr_from { get; set; }
        public Nullable<int> id_usr_to { get; set; }
        public Nullable<System.DateTime> dt_sent { get; set; }
        public string tx_message { get; set; }
    }
}
